version: "3"

services:
#===================================================================
  db:
    image: mariadb:10.7.3  #如若此镜像在你的平台上不可用，可以自行在docker hub上搜索你平台可用的mariadb镜像
    environment:
      - MYSQL_DATABASE=tiebacloud
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
#===================================================================
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_PASSWORD=1qaz2wsx
      - PMA_PORTS=3306
      - PMA_USER=root
      - PMA_VERBOSES=db # 自定义名字
    ports:
      - 9092:80
#===================================================================
  adguardhome:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /data/adguardhome/work:/opt/adguardhome/work:rw
      - /data/adguardhome/conf:/opt/adguardhome/conf:rw
    network_mode: "host"
#===================================================================
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: always
    stdin_open: true
    tty: true
    environment:
      - TZ="Asia/Shanghai"
      # - TRANSMISSION_WEB_HOME=/combustion-release/
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      # - TRANSMISSION_WEB_HOME=/kettu/
      - USER=zxz
      - PASS=zhang.zhen
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/transmission/config:/config:rw
      - /data/transmission/downloads:/downloads:rw
      - /data/transmission/watch:/watch:rw
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
#===================================================================
  tieba-cloud-sign:
    image: moenetwork/tieba-cloud-sign
    environment:
      - PUID=1000  # 可修改为你想以什么用户运行caddy，该用户的UID
      - PGID=1000  # 可修改为你想以什么用户运行caddy，该用户的UID
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWD=1qaz2wsx  # 数据库密码
      - DB_NAME=tiebacloud  # 数据库名
      - CSRF=true
    volumes:                                        # 如果重新创建或更新镜像希望保留之前的所有信息，请解除此两行注释
      - /data/tieba-cloud-sign/install.lock:/var/www/setup/install.lock  # 在当前目录下自行新建文件install.lock，内容为：1
    ports:
      - 9095:8080
    links:
      - db
    depends_on:
      - db
#===================================================================
  homeassistant:
    image: uhub.service.ucloud.cn/naturelr/home-assistant:stable
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/homeassistant:/config:rw
    network_mode: "host"
    privileged: true
#===================================================================
