services:
#===================================================================
  db:
    image: mariadb:10.7.3  #如若此镜像在你的平台上不可用，可以自行在docker hub上搜索你平台可用的mariadb镜像
    container_name: db
    environment:
      - MYSQL_DATABASE=tiebacloud
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
    volumes:
      - /data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: always
#    ports:
#      - 6379:6379
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/html:/usr/share/nginx/html
    restart: always
    ports:
      - 6080:80
#===================================================================
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_PASSWORD=1qaz2wsx
      - PMA_PORTS=3306
      - PMA_USER=root
      - PMA_VERBOSES=db # 自定义名字
    ports:
      - 6082:80
#===================================================================
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    #ports:
    #  - 6081:6081
    volumes:
      - /data/adguardhome/work:/opt/adguardhome/work:rw
      - /data/adguardhome/conf:/opt/adguardhome/conf:rw
    network_mode: "host"
#===================================================================
  transmission:
    container_name: transmission
    image: linuxserver/transmission:version-3.00-r8
    restart: always
    stdin_open: true
    tty: true
    environment:
      - TZ="Asia/Shanghai"
      # - TRANSMISSION_WEB_HOME=/combustion-release/
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      # - TRANSMISSION_WEB_HOME=/kettu/
      - USER=admin
      - PASS=1qaz2wsx
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/transmission/config:/config:rw
      - /data/transmission/downloads:/downloads:rw
      - /data/transmission/watch:/watch:rw
      - /data/transmission/ui:/ui
    ports:
      - 6085:9091
      - 51413:51413
      - 51413:51413/udp
#===================================================================
  tieba-cloud-sign:
    image: moenetwork/tieba-cloud-sign:latest
    container_name: tieba-cloud-sign
    environment:
      - PUID=1000  # 可修改为你想以什么用户运行caddy，该用户的UID
      - PGID=1000  # 可修改为你想以什么用户运行caddy，该用户的UID
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWD=1qaz2wsx  # 数据库密码
      - DB_NAME=tiebacloud  # 数据库名
      - CSRF=true
    volumes:                                        # 如果重新创建或更新镜像希望保留之前的所有信息，请解除此两行注释
      - /data/tieba-cloud-sign/install.lock:/var/www/setup/install.lock  # 在当前目录下自行新建文件install.lock，内容为：1
    restart: always
    ports:
      - 6084:8080
    links:
      - db
    depends_on:
      - db
#===================================================================
  homeassistant:
    image: ghcr.nju.edu.cn/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    #ports:
    #  - 6083:6083
    volumes:
      - /data/homeassistant:/config:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    privileged: true
#===================================================================
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - /data/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
#===================================================================
  clash:
    image: dreamacro/clash-premium:latest
    restart: always
    container_name: clash
    volumes:
      - /data/clash/:/root/.config/clash
    network_mode: "host"
    #ports:
    #  - "7890:7890"
    #  - "7891:7891"
    #  - "6086:6086"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
#===================================================================
  m3u8-downloader:
    image:  naturelingran/m3u8-downloader:latest
    restart: always
    container_name: m3u8-downloade
    ports:
      - "6087:80"
#===================================================================
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "6088:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/portainer:/data"
    restart: always
#===================================================================
#  nextcloud:
#    image: nextcloud-smb:latest
#    container_name: nextcloud
#    build: 
#      context: .
#      dockerfile: nextcloud.Dockerfile
#    volumes:
#      - /data/nextcloud/nextcloud:/var/www/html
#      - /data/nextcloud/apps:/var/www/html/custom_apps
#      - /data/nextcloud/config:/var/www/html/config
#      - /data/nextcloud/data:/var/www/html/data
#    restart: always
#    ports:
#      - 9096:80
#    links:
#    - db
#    - redis
#    depends_on:
#    - db
#    - redis
#

