version: "3"

services:
  adguardhome:
    image: uhub.service.ucloud.cn/naturelr/home-assistant:stable
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/homeassistant:/config:rw
    network_mode: "host"
