version: "3"

services:
  cloudreve:
    image: xavierniu/cloudreve:latest
    restart: always
    volumes:
      - /data/cloudreve/uploads:/cloudreve/uploads
      - /data/cloudreve/avatar:/cloudreve/avatar
      - /data/cloudreve/db:/cloudreve/db
      - /data/cloudreve/config/:/cloudreve/config/
    ports:
      - 5212:9096
