---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_ARBITRARY # 可以和任何服务器连接
          value: "1"
        - name: PMA_HOSTS # 数据库地址
          value: mysql
        - name: PMA_PASSWORD # 数据库密码
          value: "123456"
        - name: PMA_PORTS # 数据库端口
          value: "3306"
        - name: PMA_USER # 数据库账号
          value: root
        - name: PMA_VERBOSES # 自定义名字
          value: test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
    name: web
  type: NodePort
