version: "3"

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: always
    stdin_open: true
    tty: true
    environment:
      - TZ="Asia/Shanghai"
      # - TRANSMISSION_WEB_HOME=/combustion-release/
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      # - TRANSMISSION_WEB_HOME=/kettu/
      - USER=zxz
      - PASS=zhang.zhen
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/transmission/config:/config:rw
      - /data/transmission/downloads:/downloads:rw
      - /data/transmission/watch:/watch:rw
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
