version: "3"

services:
  openwrt:
    container_name: openwrt
    # image: openwrtorg/rootfs:latest
    image: openwrtorg/rootfs:armvirt-64-openwrt-21.02
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "9092:80/tcp"
      - "9093:443/tcp"
      - "9022:22/tcp"
    networks:
     # - bridge
      - eth0.10
      - eth0.20

networks:

# 把bridage网桥连进来，提供网络服务，可以在安装和更新完后把这个网络disconnect掉提高隔离度。
#  bridge:
#    external: true

# 使用macvlan将网口直通给容器。每个网口相当于一个虚拟网关，openwrt等于是上层的网关。
  eth0.10:
    driver: macvlan
    driver_opts:
      parent: eth0.10
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 192.168.233.0/24

  eth0.20:
    driver: macvlan
    driver_opts:
      parent: eth0.20
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 192.168.233.251/32

