apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluent-bit
  name: fluent-bit
  namespace: logging
spec:
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  selector:
    app: fluent-bit
  sessionAffinity: None
  type: ClusterIP

